/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Date / Time Properties");
gchar *s = N_("Date");
gchar *s = N_("Current Time:");
gchar *s = N_("00:00:00");
gchar *s = N_("Hour:");
gchar *s = N_("Minute:");
gchar *s = N_("Second:");
gchar *s = N_("Time");
gchar *s = N_("Your computer can synchronize its clock with a remote time server using the Network Time Protocol");
gchar *s = N_("_Enable Network Time Protocol");
gchar *s = N_("Server: ");
gchar *s = N_("*");
gchar *s = N_("Network Time Protocol");
gchar *s = N_("Date & Time");
gchar *s = N_("Please select the nearest city in your timezone:");
gchar *s = N_("_System clock uses UTC");
gchar *s = N_("Timezone");
